[[providers]]
name = "doronic"
type = "postgis"
uri = "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
srid = 4326

    [[providers.layers]]
    name = "occurrences"
    sql  = """
      SELECT
        taxon_key, ST_AsBinary(occurrences) AS geom
      FROM species_occurrences
      WHERE occurrences && !BBOX!
      !SPECIES_TAXON_KEY!
    """


[[maps]]
name = "occurrences"
tile_buffer = 0

    [[maps.layers]]
    provider_layer = "doronic.occurrences"

    [[maps.params]]
    name            = "species_taxon_key"
    token           = "!SPECIES_TAXON_KEY!"
    type            = "string"
    sql             = "AND taxon_key = ?"
